import uuid
from pathlib import Path
from fpdf import FPDF
from backend.config import settings

def generate_pdf_report(prediction_data: dict, user_data: dict) -> str:
    settings.REPORT_DIR.mkdir(parents=True, exist_ok=True)
    report_filename = f"report_{uuid.uuid4().hex}.pdf"
    report_path = settings.REPORT_DIR / report_filename

    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "AI Skin Disease Preliminary Diagnosis Report", ln=True, align='C')
    pdf.ln(5)
    
    # Patient Info
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Patient Information:", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.cell(0, 8, f"Username: {user_data.get('username', 'N/A')}", ln=True)
    pdf.cell(0, 8, f"Email: {user_data.get('email', 'N/A')}", ln=True)
    pdf.cell(0, 8, f"Date: {prediction_data.get('created_at', 'N/A')}", ln=True)
    pdf.ln(5)
    
    # Images
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Uploaded Image & Grad-CAM Heatmap:", ln=True)
    
    y = pdf.get_y()
    
    img_path = prediction_data.get('image_path')
    if img_path and Path(img_path).exists():
        pdf.image(img_path, x=15, y=y, w=80)
        
    gradcam_path = prediction_data.get('gradcam_path')
    if gradcam_path and Path(gradcam_path).exists():
        pdf.image(gradcam_path, x=105, y=y, w=80)
        
    pdf.set_y(y + 85)
    
    # Prediction Results
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, "Diagnosis Results:", ln=True)
    pdf.set_font("Arial", '', 11)
    
    pdf.cell(0, 8, f"Primary Prediction: {prediction_data.get('predicted_class')}", ln=True)
    pdf.cell(0, 8, f"Confidence: {prediction_data.get('confidence', 0):.2%}", ln=True)
    pdf.ln(3)
    
    # Disease Info
    info = prediction_data.get('disease_info', {})
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, f"ICD-10 Code: {info.get('icd10', 'N/A')}", ln=True)
    pdf.cell(0, 8, f"Severity: {info.get('severity', 'N/A')}", ln=True)
    pdf.ln(2)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, "Description:", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, info.get('description', 'N/A'))
    pdf.ln(2)
    
    pdf.set_font("Arial", 'B', 11)
    pdf.cell(0, 8, "Medical Advice:", ln=True)
    pdf.set_font("Arial", '', 11)
    pdf.multi_cell(0, 6, info.get('advice', 'N/A'))
    pdf.ln(5)
    
    # Disclaimer
    pdf.set_font("Arial", 'I', 9)
    pdf.set_text_color(200, 50, 50)
    pdf.multi_cell(0, 5, "[!] DISCLAIMER: This report is generated by an AI model for preliminary screening purposes only. It is not a definitive medical diagnosis. Please consult a qualified dermatologist or healthcare professional.")
    
    pdf.output(str(report_path))
    return str(report_path)
